### ISSUE TITLE
Fresh install with firefox: An unexpected error occured

### ISSUE THREAD

**Issue by pgaxatte** [gopasspw/gopassbridge#241]
Hello,

Did a fresh install recently and gopassbridge says "An unexpected error occured" and points to the documentation to setup gopass-jsonapi.

Versions:
- gopass:  `gopass 1.15.8-git+HEAD go1.21.1 linux amd64`
- gopass-jsonapi: `gopass-jsonapi version 1.15.5`
- gopassbridge: `0.9.0`

More info:
- gopass works without issues
- fresh profile on firefox
- ran `gopass-jsonapi configure`, resulting manifest and wrapper:
```
$ cat .mozilla/native-messaging-hosts/com.justwatch.gopass.json
{
    "name": "com.justwatch.gopass",
    "description": "Gopass wrapper to search and return passwords",
    "path": "/home/pgaxatte/.config/gopass/gopass_wrapper.sh",
    "type": "stdio",
    "allowed_extensions": [
        "{eec37db0-22ad-4bf1-9068-5ae08df8c7e9}"
    ]
}

$ cat "/home/pgaxatte/.config/gopass/gopass_wrapper.sh"
#!/bin/sh

export PATH="$PATH:$HOME/.nix-profile/bin" # required for Nix
export PATH="$PATH:/usr/local/bin" # required on MacOS/brew
export PATH="$PATH:/usr/local/MacGPG2/bin" # required on MacOS/GPGTools GPGSuite
export GPG_TTY="$(tty)"

# Uncomment to debug gopass-jsonapi
# export GOPASS_DEBUG_LOG=/tmp/gopass-jsonapi.log

if [ -f ~/.gpg-agent-info ] && [ -n "$(pgrep gpg-agent)" ]; then
        source ~/.gpg-agent-info
        export GPG_AGENT_INFO
else
        eval $(gpg-agent --daemon)
fi

export PATH="$PATH:/usr/local/bin"

/home/pgaxatte/go/bin/gopass-jsonapi listen

exit $?
```

How can I collect more info / find out where the issue is?

**Comment by pgaxatte** [comment]
Forgot some additional info that might be interesting:
- OS is Ubuntu 22.04, 64bits
- Firefox version 117.0.1

**Comment by gforsyth** [comment]
I just spent 2 days banging my head against this. 

It's because of the Firefox AppArmor profile in Ubuntu 22.04 -- this can be the case for both the snap version of Firefox and also for the mozilla PPA version of Firefox.

To confirm, first stop apparmor, then restart Firefox to see if `gopassbridge` is working:

```
sudo systemctl stop apparmor.service
```

If that fixes things AND you want AppArmor running:

Disable the Firefox AppArmor profile:
(note this assumes you are using the PPA firefox, not the snap Firefox.  if it's the Snap firefox the path to the apparmor profile will be different)

```
sudo ln -s /etc/apparmor.d/usr.bin.firefox /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/usr.bin.firefox
```

Restart AppArmor

```
sudo systemctl start apparmor.service
```

Then restart Firefox and things should be working.

**Comment by pgaxatte** [comment]
I stopped apparmor and restarted firefox but I still get the unexpected error.
How can I dig this any further?

**Comment by cfenell** [comment]
Same issue here, Ubuntu 22.04, Firefox 117 from snap.
The browser console logs:
    NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) 
    [NativeMessaging.sys.mjs:361](resource://gre/modules/NativeMessaging.sys.mjs)
    [nsINativeMessagingPortal.closeSession]
Hope this is of some help.

**Comment by cfenell** [comment]
Update: I changed from snap to PPA package and see a different error message:
    normalizeError resource://gre/modules/ExtensionCommon.sys.mjs:817

**Comment by cfenell** [comment]
It turned out that 
   sudo systemctl stop apparmor.service 
did not work for men, but what does work is:
  sudo apt install apparmor-utils
  sudo aa-complain usr.bin.firefox
